# .github\workflows\main_os2data-webhook.yml
name: Build and deploy Python app to Azure Web App - os2data-webhook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

        
      - name: Installer dependencies
        run: |
          echo "Installing dependencies..."
          cd /home/runner/work/os2data/os2data  # Replace with your repository path if different
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt --target ./deploy
          echo "Dependencies installed successfully."

      - name: Forbereder deployment package...
        run: |
          echo " Forbereder deployment package..."
          mkdir -p ./deploy
          cp -r app.py wsgi.py database_handler.py requirements.txt startup.sh gunicorn.conf.py ./deploy/
          echo " Deployment package indhold:"
          ls -la ./deploy/
          echo " Deployment package er klar"


      - name: Make startup.sh executable
        run: chmod +x ./deploy/startup.sh

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'os2data-webhook'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C1187D2CCC284570A40A76220A65C4AF }}
          package: './deploy'
        env:
          SVAR_ASSIST_DB_CONNECTION: "mssql+pyodbc://svarassist.database.windows.net:1433/Paragraf_8_Ansogning?driver=ODBC+Driver+18+for+SQL+Server&authentication=ActiveDirectoryMsi&encrypt=yes&trustservercertificate=no"